/*
 * algorithm_error_codes.h
 *
 *  Created on: 19.12.2014
 *      Author: Ludmila
 */

#ifndef ALGORITHM_ERROR_CODES_H_
#define ALGORITHM_ERROR_CODES_H_

enum _AlgorithmErrorCodes
{
	NO_ALGORITHM_ERROR 		= 0,
	ALGORITHM_ERROR_CODE_1	= 1,
	ALGORITHM_ERROR_CODE_2,
	ALGORITHM_ERROR_CODE_3,
	ALGORITHM_ERROR_CODE_4,
	ALGORITHM_ERROR_CODE_5,
	ALGORITHM_ERROR_CODE_6,
	ALGORITHM_ERROR_CODE_7,
};

#endif /* ALGORITHM_ERROR_CODES_H_ */
