/*
 * programm_errors.h
 *
 *  Created on: 24.12.2014
 *      Author: Ludmila
 */

#ifndef PROGRAMM_ERRORS_H_
#define PROGRAMM_ERRORS_H_

enum PmoErrorCodes
{
	NO_PMO_ERROR 			= 0,
	ALGORITHM_ERROR_CODE_1	= 1,
	ALGORITHM_ERROR_CODE_2,
	ALGORITHM_ERROR_CODE_3,
	ALGORITHM_ERROR_CODE_4,
	ALGORITHM_ERROR_CODE_5,
	ALGORITHM_ERROR_CODE_6,
	ALGORITHM_ERROR_CODE_7,
};

#endif /* PROGRAMM_ERRORS_H_ */
